require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'watermelonPOC' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  target 'watermelonPOCTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'watermelonPOC-tvOS' do
  # Pods for watermelonPOC-tvOS

  target 'watermelonPOC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
