import {mapValues, omit} from 'lodash';

export function getMockData() {
  return mapValues(generateData(), (table) =>
    mapValues(table, (changeType) =>
      changeType.map((entry) => ({...omit(entry, ['_status', '_changed'])})),
    ),
  );
}

function generateData() {
  return {
    blogs: {
      created: [
        {
          id: '66hfstnduj19np4p',
          _status: 'created',
          _changed: '',
          name: 'Ars Technica',
        },
        {
          id: '1yibwqdqen1kjj1i',
          _status: 'created',
          _changed: '',
          name: 'Anandtech',
        },
      ],
      updated: [],
      deleted: [],
    },
    posts: {
      created: [
        {
          id: 'je6ebsszywu6h1pm',
          _status: 'created',
          _changed: '',
          title: 'TSB boss to step down after IT fiasco (bbc.com)',
          subtitle: 'ID: je6ebsszywu6h1pm',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: 'e33d1505kcoxdxm6',
          _status: 'created',
          _changed: '',
          title:
            'Show HN: Select Star SQL, an interactive SQL book (selectstarsql.com)',
          subtitle: 'ID: e33d1505kcoxdxm6',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: 'c971p7q6i1yyy6ck',
          _status: 'created',
          _changed: '',
          title:
            'Want to Be More Creative? Take a Walk (2014) (well.blogs.nytimes.com)',
          subtitle: 'ID: c971p7q6i1yyy6ck',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: 'azajixddiwbn3tey',
          _status: 'created',
          _changed: '',
          title: 'Stellarium Web: Online Planetarium (stellarium-web.org)',
          subtitle: 'ID: azajixddiwbn3tey',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: 'c6wtopm6a4m001rp',
          _status: 'created',
          _changed: '',
          title: 'How LLVM Optimizes a Function (regehr.org)',
          subtitle: 'ID: c6wtopm6a4m001rp',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: '1bgsfb85ljndyps5',
          _status: 'created',
          _changed: '',
          title:
            'A military technique for falling asleep in two minutes (independent.co.uk)',
          subtitle: 'ID: 1bgsfb85ljndyps5',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: '4slbtj6avdajyfxw',
          _status: 'created',
          _changed: '',
          title:
            'A Fighter Pilot’s Guide to Surviving on the Roads (portsmouthctc.org.uk)',
          subtitle: 'ID: 4slbtj6avdajyfxw',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: '5st8zqt3ypcmxi5x',
          _status: 'created',
          _changed: '',
          title:
            'Tencent loses $20B in value after China attacks myopia with gaming curbs (channelnewsasia.com)',
          subtitle: 'ID: 5st8zqt3ypcmxi5x',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '66hfstnduj19np4p',
        },
        {
          id: 'g812mf7uoqs41sm9',
          _status: 'created',
          _changed: '',
          title: 'TSB boss to step down after IT fiasco (bbc.com)',
          subtitle: 'ID: g812mf7uoqs41sm9',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: 'y5ndjlgum5qqv1ux',
          _status: 'created',
          _changed: '',
          title:
            'Show HN: Select Star SQL, an interactive SQL book (selectstarsql.com)',
          subtitle: 'ID: y5ndjlgum5qqv1ux',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: '1cvrfh3k5uqq078n',
          _status: 'created',
          _changed: '',
          title:
            'Want to Be More Creative? Take a Walk (2014) (well.blogs.nytimes.com)',
          subtitle: 'ID: 1cvrfh3k5uqq078n',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: '382zv9jnp6euak47',
          _status: 'created',
          _changed: '',
          title: 'Stellarium Web: Online Planetarium (stellarium-web.org)',
          subtitle: 'ID: 382zv9jnp6euak47',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: 'pttjdjoy4suhqz5n',
          _status: 'created',
          _changed: '',
          title: 'How LLVM Optimizes a Function (regehr.org)',
          subtitle: 'ID: pttjdjoy4suhqz5n',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: 'a4a96931se0txzo9',
          _status: 'created',
          _changed: '',
          title:
            'A military technique for falling asleep in two minutes (independent.co.uk)',
          subtitle: 'ID: a4a96931se0txzo9',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
        {
          id: 's0ow2gf7mnx6g8ib',
          _status: 'created',
          _changed: '',
          title:
            'A Fighter Pilot’s Guide to Surviving on the Roads (portsmouthctc.org.uk)',
          subtitle: 'ID: s0ow2gf7mnx6g8ib',
          body:
            'Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Lorem ipsum dolor sit amet enim. Etiam ullamcorper. Suspendisse a pellentesque dui, non felis. Maecenas malesuada elit lectus felis, malesuada ultricies. Curabitur et ligula. Ut molestie a, ultricies porta urna. Vestibulum commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor. Pellentesque facilisis. Nulla imperdiet sit amet magna. Vestibulum dapibus, mauris nec malesuada fames ac turpis velit, rhoncus eu, luctus et interdum adipiscing wisi. Aliquam erat ac ipsum. Integer aliquam purus. Quisque lorem tortor fringilla sed, vestibulum id, eleifend justo vel bibendum sapien massa ac turpis faucibus orci luctus non, consectetuer lobortis quis, varius in, purus. Integer ultrices posuere cubilia Curae, Nulla ipsum dolor lacus, suscipit adipiscing. Cum sociis natoque penatibus et ultrices volutpat.',
          blog_id: '1yibwqdqen1kjj1i',
        },
      ],
      updated: [],
      deleted: [],
    },
    comments: {
      created: [
        {
          id: 'chc21j4imhzbc566',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'je6ebsszywu6h1pm',
          is_nasty: true,
        },
        {
          id: '3n84zffv07ltj1d7',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'je6ebsszywu6h1pm',
          is_nasty: false,
        },
        {
          id: 'hf403p0tuffzc4r7',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'je6ebsszywu6h1pm',
          is_nasty: true,
        },
        {
          id: '2vqfon291ka0gyyy',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'je6ebsszywu6h1pm',
          is_nasty: true,
        },
        {
          id: '6eu8ws0idqnblu1o',
          _status: 'created',
          _changed: '',
          body: 'seriously one of the coolest projects going on right now',
          post_id: 'je6ebsszywu6h1pm',
          is_nasty: false,
        },
        {
          id: 'zzq10z7ho60s4rba',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'e33d1505kcoxdxm6',
          is_nasty: false,
        },
        {
          id: '5ple9cklxc1ggpyn',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'e33d1505kcoxdxm6',
          is_nasty: false,
        },
        {
          id: '9yne5jc5wrai9mhy',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'e33d1505kcoxdxm6',
          is_nasty: false,
        },
        {
          id: 'kl7mtsmk12xjp90g',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'e33d1505kcoxdxm6',
          is_nasty: false,
        },
        {
          id: 'nm45k8vzcavbiqij',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'c971p7q6i1yyy6ck',
          is_nasty: false,
        },
        {
          id: '3lawo8tvxixhezwr',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'azajixddiwbn3tey',
          is_nasty: false,
        },
        {
          id: 'qcq0ro9gukj5felb',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'azajixddiwbn3tey',
          is_nasty: false,
        },
        {
          id: 'r6fdzve1s5kv8b6b',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'azajixddiwbn3tey',
          is_nasty: false,
        },
        {
          id: 'ezucy9wjh6d3ytzh',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'azajixddiwbn3tey',
          is_nasty: true,
        },
        {
          id: 'lc1rk8bq0y8iqew8',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'c6wtopm6a4m001rp',
          is_nasty: false,
        },
        {
          id: 'xgxaa9nxb23x6o2k',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: '1bgsfb85ljndyps5',
          is_nasty: false,
        },
        {
          id: 'wk6im9mup37gvr23',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: '1bgsfb85ljndyps5',
          is_nasty: false,
        },
        {
          id: 'wi09rv09s1a0a02q',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: 'a3txz840sponra8l',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: 'jttnbna674nagdti',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: true,
        },
        {
          id: '5n26ti91ge9z363i',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: '6zfat8750nf2wwkk',
          _status: 'created',
          _changed: '',
          body: 'seriously one of the coolest projects going on right now',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: 'pciwef2nx1lgpugh',
          _status: 'created',
          _changed: '',
          body:
            'I think easiest way is just to write a backend that emits .NET IR since infra is already there.',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: 'm3da4h2sq8h86eir',
          _status: 'created',
          _changed: '',
          body: 'Open source?',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: true,
        },
        {
          id: 'r1a6821hds3ek35s',
          _status: 'created',
          _changed: '',
          body: 'This article is obviously wrong',
          post_id: '4slbtj6avdajyfxw',
          is_nasty: false,
        },
        {
          id: '30smj2i79jk9nxqn',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: '5st8zqt3ypcmxi5x',
          is_nasty: false,
        },
        {
          id: 'j0cpo95q4tn96fug',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: '5st8zqt3ypcmxi5x',
          is_nasty: false,
        },
        {
          id: 'kfpopiq9bvtjkxw1',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'g812mf7uoqs41sm9',
          is_nasty: false,
        },
        {
          id: '7imsukz4h2ngndjn',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'g812mf7uoqs41sm9',
          is_nasty: false,
        },
        {
          id: '6o2ppk19sab7avte',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'g812mf7uoqs41sm9',
          is_nasty: true,
        },
        {
          id: 'zgkd856f1x28db45',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'g812mf7uoqs41sm9',
          is_nasty: false,
        },
        {
          id: 'jjbriy2i1x2gp988',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'y5ndjlgum5qqv1ux',
          is_nasty: false,
        },
        {
          id: 'ipw3yacbfy22mik7',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'y5ndjlgum5qqv1ux',
          is_nasty: false,
        },
        {
          id: 'dg4kgc82zmrl3tyu',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: '1cvrfh3k5uqq078n',
          is_nasty: false,
        },
        {
          id: '00co4ats5wcptk6z',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: '1cvrfh3k5uqq078n',
          is_nasty: false,
        },
        {
          id: 'bycvgmw6tdfscpx3',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: '1cvrfh3k5uqq078n',
          is_nasty: false,
        },
        {
          id: '7dpo7nxi4adhm0oh',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: '382zv9jnp6euak47',
          is_nasty: false,
        },
        {
          id: 'wpzf9ha0j256epde',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: '382zv9jnp6euak47',
          is_nasty: true,
        },
        {
          id: '2rhynqgiyrpu1mez',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: '382zv9jnp6euak47',
          is_nasty: true,
        },
        {
          id: 'hvau2pzt10n3dxcs',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: '382zv9jnp6euak47',
          is_nasty: true,
        },
        {
          id: '8cebq41ikl2oyomu',
          _status: 'created',
          _changed: '',
          body: 'seriously one of the coolest projects going on right now',
          post_id: '382zv9jnp6euak47',
          is_nasty: false,
        },
        {
          id: 'e6r1roo42cjws0ky',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'pttjdjoy4suhqz5n',
          is_nasty: false,
        },
        {
          id: 'lzrrvtevcfx6xmpj',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'pttjdjoy4suhqz5n',
          is_nasty: true,
        },
        {
          id: 'b5j5v7o1bnw3rdss',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'pttjdjoy4suhqz5n',
          is_nasty: false,
        },
        {
          id: '0cgdl4gbykyxadom',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'pttjdjoy4suhqz5n',
          is_nasty: false,
        },
        {
          id: 'a5ihpsuftjj2uvtg',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 'a4a96931se0txzo9',
          is_nasty: true,
        },
        {
          id: 'zg7akv6sdqmjmka2',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 'a4a96931se0txzo9',
          is_nasty: false,
        },
        {
          id: '2k9ashhl2wdir8v0',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 'a4a96931se0txzo9',
          is_nasty: true,
        },
        {
          id: 'q05sy78fnxux0ber',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 'a4a96931se0txzo9',
          is_nasty: false,
        },
        {
          id: 'lj7zqa50izdxxlwp',
          _status: 'created',
          _changed: '',
          body: 'First!!!!',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: false,
        },
        {
          id: '1vmn8876lpvyqll1',
          _status: 'created',
          _changed: '',
          body: 'Cool!',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: false,
        },
        {
          id: 'o4n4dbw6i0dsmr77',
          _status: 'created',
          _changed: '',
          body: 'Why dont you just…',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: true,
        },
        {
          id: 'jin8ajipqxvhgk4x',
          _status: 'created',
          _changed: '',
          body:
            'Maybe useless, but the article is extremely intersting and easy to read. One can definitely try to read it.',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: true,
        },
        {
          id: '0w55zj9m1w51npf6',
          _status: 'created',
          _changed: '',
          body: 'seriously one of the coolest projects going on right now',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: false,
        },
        {
          id: 'yt4m15sd0vxv6m1z',
          _status: 'created',
          _changed: '',
          body:
            'I think easiest way is just to write a backend that emits .NET IR since infra is already there.',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: true,
        },
        {
          id: 'zkk3rzzsd47svokd',
          _status: 'created',
          _changed: '',
          body: 'Open source?',
          post_id: 's0ow2gf7mnx6g8ib',
          is_nasty: false,
        },
      ],
      updated: [],
      deleted: [],
    },
  };
}
